### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jslesk** [clover/android-examples#25]
Hi @david-clover-com ,

i would need little advice in implementing backend system in Java, if you have bit of time. I searched most of Java examples available on clover github, but all of them are connected to hardware POS device and Android. Is there any good example that is not connected to  hardware POS device or Android (just backend communicating with clover- ordering items and making payments).

If i am correct, data model classes are available only android sdk?

Greeting

**Comment by david-clover-com** [comment]
Please see our developer documentation - https://docs.clover.com/docs/home.  We also have a forum that is suited for specific questions once you have done research into what integrations are available - https://community.clover.com/index.html.
